#pragma config(Sensor, dgtl1,  encoder_left,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  encoder_right,  sensorQuadEncoder)
#pragma config(Motor,  port1,           claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           drive_left,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           left_chainbar, tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           lift_top_left, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           lift_bottom_left, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           mobile_goal_intake, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           drive_right,   tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           lift_top_right, tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           lift_bottom_right, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          right_chainbar, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"



void pre_auton()
{
	bStopTasksBetweenModes = true;
}


task autonomous() // LEFT SIDE 5
{
	motor[claw] = 63;
	motor[lift_bottom_left] = 127;
	motor[lift_bottom_right] = 127;
	motor[lift_top_right] = 127;
	motor[lift_top_left] = 127;
	motor[mobile_goal_intake] = -127;	// put mobile goal intake down
	wait1Msec(400); // lasting period
	motor[mobile_goal_intake] = 0; // stop
	motor[lift_bottom_left] = 15;
	motor[lift_bottom_right] = 15;
	motor[lift_top_right] = 15;
	motor[lift_top_left] = 15;


	motor[mobile_goal_intake] = -127;	// put mobile goal intake down
	wait1Msec(600); // lasting period
	motor[mobile_goal_intake] = -20; // stop

	SensorValue[encoder_left] = 0; // (reset encoder)
	SensorValue[encoder_right] = 0; // (reset encoder)

	while(abs(SensorValue[encoder_right]) < 1320 && abs(SensorValue[encoder_left]) < 1320) // drive forward to mobile goal
	{
		motor[drive_right] = 127; //motor power
		motor[drive_left] = 127; //motor power
	}
	motor[drive_right] = 0; // stop
	motor[drive_left] = 0; // stop


	motor(mobile_goal_intake) = 127;	// pick up mobile goal
	wait1Msec(1350); // lasting period
	motor(mobile_goal_intake) = 0; //stop
	motor[lift_bottom_left] = 15;
	motor[lift_bottom_right] = 15;
	motor[lift_top_right] = 15;
	motor[lift_top_left] = 15;


	motor[left_chainbar] = -127;
	motor[right_chainbar] = 127;
	wait1Msec(100);
	motor[left_chainbar] = 0;
	motor[right_chainbar] = 0;
	wait1Msec(400);


	motor[claw] = -127;
	wait1Msec(70);
	motor[claw] = 0;
	wait1Msec(200);


	SensorValue[encoder_right] = 0; // (reset encoder)
	SensorValue[encoder_left] = 0; // (reset encoder)

	while(abs(SensorValue[encoder_right]) < 200 && abs(SensorValue[encoder_left]) < 200) // drive forward to the cone
	{
		motor[drive_left] = 127; // motor power
		motor[drive_right] = 127; // motor power
	}
	motor[drive_left] = 0; // stop
	motor[drive_right] = 0; // stop


	motor[left_chainbar] = -127;
	motor[right_chainbar] = 127;
	wait1Msec(600); // lasting period
	motor[claw] = 127; // claw


	motor[lift_bottom_left] = -15;
	motor[lift_bottom_right] = -15;
	motor[lift_top_right] = -15;
	motor[lift_top_left] = -15;


	motor[claw] = 127; // claw grab
	wait1Msec(500); // lasting period
	motor[left_chainbar] = 127;
	motor[right_chainbar] = -127;
	motor[lift_bottom_left] = 127;
	motor[lift_bottom_right] = 127;
	motor[lift_top_right] = 127;
	motor[lift_top_left] = 127;
	wait1Msec(400); // lasting period
	motor[lift_bottom_left] = 0;
	motor[lift_bottom_right] = 0;
	motor[lift_top_right] = 0;
	motor[lift_top_left] = 0;
	motor[left_chainbar] = 127;
	motor[right_chainbar] = -127;
	wait1Msec(600);
	motor[left_chainbar] = 0; // stop
	motor[right_chainbar] = 0; // stop
	wait1Msec(200);


	motor[claw] = -127;
	motor[lift_bottom_left] = 40;
	motor[lift_bottom_right] = 40;
	motor[lift_top_right] = 40;
	motor[lift_top_left] = 40;
	wait1Msec(200);
	motor[claw] = 0;


	SensorValue[encoder_right] = 0; // (reset encoder)
	SensorValue[encoder_left] = 0; // (reset encoder)

	while(abs(SensorValue[encoder_right]) < 550 && abs(SensorValue[encoder_left]) < 550) // drive back
	{
		motor[drive_left] = -127; // motor power
		motor[drive_right] = -127; // motor power
	}
	motor[drive_left] = 0; // stop
	motor[drive_right] = 0; // stop


	SensorValue[encoder_right] = 0; //(reset encoder)
	SensorValue[encoder_left] = 0; //(reset encoder)

	while(abs(SensorValue[encoder_left]) < 850)
	{
		motor[drive_left] = -127; // motor power
	}
	motor[drive_left] = 0; // stop


	SensorValue[encoder_right] = 0; //(reset encoder)
	SensorValue[encoder_left] = 0; //(reset encoder)

	while(abs(SensorValue[encoder_right]) < 550 && abs(SensorValue[encoder_left]) < 550) // drive back
	{
		motor[drive_left] = -127; // motor power
		motor[drive_right] = 127; // motor power
	}
	motor[drive_left] = 0; // stop
	motor[drive_right] = 0; // stop


	motor[right_chainbar] = 127;
	motor[left_chainbar] = -127;
	wait1Msec(60);
	motor[right_chainbar] = 0;
	motor[left_chainbar] = 0;


	motor[mobile_goal_intake] = -127; // put mobile goal intake down
	wait1Msec(1250); // lasting period
	motor[mobile_goal_intake] = 0; // stop


	motor[drive_left] = -60; // drive back from the mobile goal
	motor[drive_right] = -60; // drive back from the mobile goal
	wait1Msec(300); // lasting period
	motor[mobile_goal_intake] = 127;
	wait1Msec(100);
	motor[drive_left] = 0; // stop
	motor[drive_right] = 0; // stop
	motor[mobile_goal_intake] = 0;


	motor[drive_left] = -127; // drive back from the mobile goal
	motor[drive_right] = -127; // drive back from the mobile goal
	wait1Msec(300); // lasting period
	motor[drive_left] = 0; // stop
	motor[drive_right] = 0; // stop

}




/*
task autonomous() // RIGHT SIDE 5
{
motor[claw] = 63;
motor[lift_bottom_left] = 127;
motor[lift_bottom_right] = 127;
motor[lift_top_right] = 127;
motor[lift_top_left] = 127;
motor[mobile_goal_intake] = -127;	// put mobile goal intake down
wait1Msec(400); // lasting period
motor[mobile_goal_intake] = 0; // stop
motor[lift_bottom_left] = 15;
motor[lift_bottom_right] = 15;
motor[lift_top_right] = 15;
motor[lift_top_left] = 15;


motor[mobile_goal_intake] = -127;	// put mobile goal intake down
wait1Msec(600); // lasting period
motor[mobile_goal_intake] = -20; // stop

SensorValue[encoder_left] = 0; // (reset encoder)
SensorValue[encoder_right] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 1320 && abs(SensorValue[encoder_left]) < 1320) // drive forward to mobile goal
{
motor[drive_right] = 127; //motor power
motor[drive_left] = 127; //motor power
}
motor[drive_right] = 0; // stop
motor[drive_left] = 0; // stop


motor(mobile_goal_intake) = 127;	// pick up mobile goal
wait1Msec(1350); // lasting period
motor(mobile_goal_intake) = 0; //stop
motor[lift_bottom_left] = 15;
motor[lift_bottom_right] = 15;
motor[lift_top_right] = 15;
motor[lift_top_left] = 15;


motor[left_chainbar] = -127;
motor[right_chainbar] = 127;
wait1Msec(100);
motor[left_chainbar] = 0;
motor[right_chainbar] = 0;
wait1Msec(400);


motor[claw] = -127;
wait1Msec(70);
motor[claw] = 0;
wait1Msec(200);


SensorValue[encoder_right] = 0; // (reset encoder)
SensorValue[encoder_left] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 200 && abs(SensorValue[encoder_left]) < 200) // drive forward to the cone
{
motor[drive_left] = 127; // motor power
motor[drive_right] = 127; // motor power
}
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop


motor[left_chainbar] = -127;
motor[right_chainbar] = 127;
wait1Msec(600); // lasting period
motor[claw] = 127; // claw


motor[lift_bottom_left] = -15;
motor[lift_bottom_right] = -15;
motor[lift_top_right] = -15;
motor[lift_top_left] = -15;


motor[claw] = 127; // claw grab
wait1Msec(500); // lasting period
motor[left_chainbar] = 127;
motor[right_chainbar] = -127;
motor[lift_bottom_left] = 127;
motor[lift_bottom_right] = 127;
motor[lift_top_right] = 127;
motor[lift_top_left] = 127;
wait1Msec(400); // lasting period
motor[lift_bottom_left] = 0;
motor[lift_bottom_right] = 0;
motor[lift_top_right] = 0;
motor[lift_top_left] = 0;
motor[left_chainbar] = 127;
motor[right_chainbar] = -127;
wait1Msec(600);
motor[left_chainbar] = 0; // stop
motor[right_chainbar] = 0; // stop
wait1Msec(200);


motor[claw] = -127;
motor[lift_bottom_left] = 40;
motor[lift_bottom_right] = 40;
motor[lift_top_right] = 40;
motor[lift_top_left] = 40;
wait1Msec(200);
motor[claw] = 0;


SensorValue[encoder_right] = 0; // (reset encoder)
SensorValue[encoder_left] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 720 && abs(SensorValue[encoder_left]) < 720) // drive back
{
motor[drive_left] = -127; // motor power
motor[drive_right] = -127; // motor power
}
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop


SensorValue[encoder_right] = 0; //(reset encoder)
SensorValue[encoder_left] = 0; //(reset encoder)

while(abs(SensorValue[encoder_right]) < 400 && abs(SensorValue[encoder_left]) < 400) // drive back
{
motor[drive_left] = 127; // motor power
motor[drive_right] = -127; // motor power
}
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop


motor[right_chainbar] = 127;
motor[left_chainbar] = -127;
wait1Msec(60);
motor[right_chainbar] = 0;
motor[left_chainbar] = 0;


motor[mobile_goal_intake] = -127; // put mobile goal intake down
wait1Msec(1250); // lasting period
motor[mobile_goal_intake] = 0; // stop


motor[drive_left] = -60; // drive back from the mobile goal
motor[drive_right] = -60; // drive back from the mobile goal
wait1Msec(300); // lasting period
motor[mobile_goal_intake] = 127;
wait1Msec(100);
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop
motor[mobile_goal_intake] = 0;


motor[drive_left] = -127; // drive back from the mobile goal
motor[drive_right] = -127; // drive back from the mobile goal
wait1Msec(300); // lasting period
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop

}
*/






/*
task autonomous() // RIGHT SIDE 10
{

motor[claw] = 63;
motor[lift_bottom_left] = 127;
motor[lift_bottom_right] = 127;
motor[lift_top_right] = 127;
motor[lift_top_left] = 127;
motor[mobile_goal_intake] = -127;	// put mobile goal intake down
wait1Msec(400); // lasting period
motor[mobile_goal_intake] = 0; // stop
motor[lift_bottom_left] = 15;
motor[lift_bottom_right] = 15;
motor[lift_top_right] = 15;
motor[lift_top_left] = 15;


motor[mobile_goal_intake] = -127;	// put mobile goal intake down
wait1Msec(600); // lasting period
motor[mobile_goal_intake] = -20; // stop

SensorValue[encoder_left] = 0; // (reset encoder)
SensorValue[encoder_right] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 1320 && abs(SensorValue[encoder_left]) < 1320) // drive forward to mobile goal
{
motor[drive_right] = 127; //motor power
motor[drive_left] = 127; //motor power
}
motor[drive_right] = 0; // stop
motor[drive_left] = 0; // stop


motor(mobile_goal_intake) = 127;	// pick up mobile goal
wait1Msec(1350); // lasting period
motor(mobile_goal_intake) = 0; //stop
motor[lift_bottom_left] = 15;
motor[lift_bottom_right] = 15;
motor[lift_top_right] = 15;
motor[lift_top_left] = 15;


motor[left_chainbar] = -127;
motor[right_chainbar] = 127;
wait1Msec(100);
motor[left_chainbar] = 0;
motor[right_chainbar] = 0;
wait1Msec(400);


motor[claw] = -127;
wait1Msec(70);
motor[claw] = 0;
wait1Msec(200);


SensorValue[encoder_right] = 0; // (reset encoder)
SensorValue[encoder_left] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 200 && abs(SensorValue[encoder_left]) < 200) // drive forward to the cone
{
motor[drive_left] = 127; // motor power
motor[drive_right] = 127; // motor power
}
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop


motor[left_chainbar] = -127;
motor[right_chainbar] = 127;
wait1Msec(600); // lasting period
motor[claw] = 127; // claw


motor[lift_bottom_left] = -15;
motor[lift_bottom_right] = -15;
motor[lift_top_right] = -15;
motor[lift_top_left] = -15;


motor[claw] = 127; // claw grab
wait1Msec(500); // lasting period
motor[left_chainbar] = 127;
motor[right_chainbar] = -127;
motor[lift_bottom_left] = 127;
motor[lift_bottom_right] = 127;
motor[lift_top_right] = 127;
motor[lift_top_left] = 127;
wait1Msec(400); // lasting period
motor[lift_bottom_left] = 0;
motor[lift_bottom_right] = 0;
motor[lift_top_right] = 0;
motor[lift_top_left] = 0;
motor[left_chainbar] = 127;
motor[right_chainbar] = -127;
wait1Msec(600);
motor[left_chainbar] = 0; // stop
motor[right_chainbar] = 0; // stop
wait1Msec(200);


motor[claw] = -127;
motor[lift_bottom_left] = 40;
motor[lift_bottom_right] = 40;
motor[lift_top_right] = 40;
motor[lift_top_left] = 40;
wait1Msec(200);
motor[claw] = 0;


SensorValue[encoder_right] = 0; // (reset encoder)
SensorValue[encoder_left] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 1020 && abs(SensorValue[encoder_left]) < 1020) // drive back
{
motor[drive_left] = -127; // motor power
motor[drive_right] = -127; // motor power
}
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop


SensorValue[encoder_right] = 0; //(reset encoder)
SensorValue[encoder_left] = 0; //(reset encoder)

while(abs(SensorValue[encoder_right]) < 1400)	// turn around facing the left side of the 10-point zone
{
motor[drive_right] = -127; // motor power
}
motor[drive_right] = 0; // stop


SensorValue[encoder_right] = 0; //(reset encoder)
SensorValue[encoder_left] = 0; //(reset encoder)

while(abs(SensorValue[encoder_left]) < 500)	// turn around facing the left side of the 10-point zone
{
motor[drive_left] = 127; // motor power
}
motor[drive_left] = 0; // stop


motor[right_chainbar] = 127;
motor[left_chainbar] = -127;
wait1Msec(60);
motor[right_chainbar] = 0;
motor[left_chainbar] = 0;


motor[mobile_goal_intake] = -127; // put mobile goal intake down
wait1Msec(1250); // lasting period
motor[mobile_goal_intake] = 0; // stop


motor[drive_left] = -60; // drive back from the mobile goal
motor[drive_right] = -60; // drive back from the mobile goal
wait1Msec(300); // lasting period
motor[mobile_goal_intake] = 127;
wait1Msec(100);
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop
motor[mobile_goal_intake] = 0;


motor[drive_left] = -127; // drive back from the mobile goal
motor[drive_right] = -127; // drive back from the mobile goal
wait1Msec(300); // lasting period
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop


}*/

/*
task autonomous() // LEFT SIDE 10

{

motor[claw] = 63;
motor[lift_bottom_left] = 127;
motor[lift_bottom_right] = 127;
motor[lift_top_right] = 127;
motor[lift_top_left] = 127;
motor[mobile_goal_intake] = -127;	// put mobile goal intake down
wait1Msec(400); // lasting period
motor[mobile_goal_intake] = 0; // stop
motor[lift_bottom_left] = 15;
motor[lift_bottom_right] = 15;
motor[lift_top_right] = 15;
motor[lift_top_left] = 15;


motor[mobile_goal_intake] = -127;	// put mobile goal intake down
wait1Msec(600); // lasting period
motor[mobile_goal_intake] = -20; // stop

SensorValue[encoder_left] = 0; // (reset encoder)
SensorValue[encoder_right] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 1320 && abs(SensorValue[encoder_left]) < 1320) // drive forward to mobile goal
{
motor[drive_right] = 127; //motor power
motor[drive_left] = 127; //motor power
}
motor[drive_right] = 0; // stop
motor[drive_left] = 0; // stop


motor(mobile_goal_intake) = 127;	// pick up mobile goal
wait1Msec(1350); // lasting period
motor(mobile_goal_intake) = 0; //stop
motor[lift_bottom_left] = 15;
motor[lift_bottom_right] = 15;
motor[lift_top_right] = 15;
motor[lift_top_left] = 15;


motor[left_chainbar] = -127;
motor[right_chainbar] = 127;
wait1Msec(100);
motor[left_chainbar] = 0;
motor[right_chainbar] = 0;
wait1Msec(400);


motor[claw] = -127;
wait1Msec(70);
motor[claw] = 0;
wait1Msec(200);


SensorValue[encoder_right] = 0; // (reset encoder)
SensorValue[encoder_left] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 200 && abs(SensorValue[encoder_left]) < 200) // drive forward to the cone
{
motor[drive_left] = 127; // motor power
motor[drive_right] = 127; // motor power
}
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop


motor[left_chainbar] = -127;
motor[right_chainbar] = 127;
wait1Msec(600); // lasting period
motor[claw] = 127; // claw


motor[lift_bottom_left] = -15;
motor[lift_bottom_right] = -15;
motor[lift_top_right] = -15;
motor[lift_top_left] = -15;


motor[claw] = 127; // claw grab
wait1Msec(500); // lasting period
motor[left_chainbar] = 127;
motor[right_chainbar] = -127;
motor[lift_bottom_left] = 127;
motor[lift_bottom_right] = 127;
motor[lift_top_right] = 127;
motor[lift_top_left] = 127;
wait1Msec(400); // lasting period
motor[lift_bottom_left] = 0;
motor[lift_bottom_right] = 0;
motor[lift_top_right] = 0;
motor[lift_top_left] = 0;
motor[left_chainbar] = 127;
motor[right_chainbar] = -127;
wait1Msec(600);
motor[left_chainbar] = 0; // stop
motor[right_chainbar] = 0; // stop
wait1Msec(200);


motor[claw] = -127;
motor[lift_bottom_left] = 40;
motor[lift_bottom_right] = 40;
motor[lift_top_right] = 40;
motor[lift_top_left] = 40;
wait1Msec(200);
motor[claw] = 0;


SensorValue[encoder_right] = 0; // (reset encoder)
SensorValue[encoder_left] = 0; // (reset encoder)

while(abs(SensorValue[encoder_right]) < 1020 && abs(SensorValue[encoder_left]) < 1020) // drive back
{
motor[drive_left] = -127; // motor power
motor[drive_right] = -127; // motor power
}
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop


SensorValue[encoder_right] = 0; //(reset encoder)
SensorValue[encoder_left] = 0; //(reset encoder)

while(abs(SensorValue[encoder_left]) < 1400)	// turn around facing the left side of the 10-point zone
{
motor[drive_left] = -127; // motor power
}
motor[drive_left] = 0; // stop


SensorValue[encoder_right] = 0; //(reset encoder)
SensorValue[encoder_left] = 0; //(reset encoder)

while(abs(SensorValue[encoder_right]) < 500)	// turn around facing the left side of the 10-point zone
{
motor[drive_right] = 127; // motor power
}
motor[drive_right] = 0; // stop


motor[right_chainbar] = 127;
motor[left_chainbar] = -127;
wait1Msec(60);
motor[right_chainbar] = 0;
motor[left_chainbar] = 0;


motor[mobile_goal_intake] = -127; // put mobile goal intake down
wait1Msec(1250); // lasting period
motor[mobile_goal_intake] = 0; // stop


motor[drive_left] = -60; // drive back from the mobile goal
motor[drive_right] = -60; // drive back from the mobile goal
wait1Msec(300); // lasting period
motor[mobile_goal_intake] = 127;
wait1Msec(100);
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop
motor[mobile_goal_intake] = 0;


motor[drive_left] = -127; // drive back from the mobile goal
motor[drive_right] = -127; // drive back from the mobile goal
wait1Msec(300); // lasting period
motor[drive_left] = 0; // stop
motor[drive_right] = 0; // stop

}
*/
task usercontrol()	// controller setup

{

	while (true)

	{

		int X1 = vexRT[Ch3]; // forward & back drive, left joystick, main controller
		int Y1 = vexRT[Ch1]; // turn right and left, right joystick, main controller
		motor[drive_right] = X1 - Y1;
		motor[drive_left] = X1 + Y1;


		motor[lift_top_left] = vexRT[Ch3Xmtr2]; // lift, left joystick, partner controller
		motor[lift_bottom_left] = vexRT[Ch3Xmtr2]; // lift, left joystick, partner controller
		motor[lift_top_right] = vexRT[Ch3Xmtr2]; // lift, left joystick, partner controller
		motor[lift_bottom_right] = vexRT[Ch3Xmtr2]; // lift, left joystick, partner controller


		int hold;

		//Claw Hold
		if(vexRT[Btn6UXmtr2]==1) // button 6U, partner controller
		{
			motor[claw] = 127; // motor power
			hold = 0;
		}
		//Claw Let Go
		else if(vexRT[Btn6DXmtr2]==1) // button 6D, partner controller
		{
			motor[claw] = -127; // motor power
			hold = 1;
		}
		//Claw Hold On
		else if (hold == 0)
		{
			motor[claw] = 42;
		}
		else if (hold == 1)
		{
			motor[claw] = 0;
		}
		else {
			motor[claw] = 0;
		}


		if(vexRT[Btn6U]==1) // button 6U, main controller
		{
			motor[mobile_goal_intake] = 127; // motor power
		}
		else if(vexRT[Btn6D]==1) // button 6D, main controller
		{
			motor[mobile_goal_intake] = -127; // motor power
		}
		else // if buttons are not pressed
		{
			motor[mobile_goal_intake] = 0; // motor power
		}


		if(vexRT[Btn5UXmtr2]==1) // button 5U, partner controller
		{
			motor[left_chainbar] = 127; // motor power
			motor[right_chainbar] = -127; // motor power
		}
		else if(vexRT[Btn5DXmtr2]==1) // button 5D, partner controller
		{
			motor[left_chainbar] = -127; // motor power
			motor[right_chainbar] = 127; // motor power
		}
		else // if buttons are not pressed
		{
			motor[left_chainbar] = 0; // motor power
			motor[right_chainbar] = 0; // motor power
		}

	}
}	// end program
